spring.profiles.active=local
spring.application.name=spring-loom-demo

logging.level.root=info
logging.level.org.springframework.web=info

server.servlet.contextPath=/spring-loom-demo

# Actuator endpoint
management.endpoints.access.default=none
management.endpoint.health.access=read_only